
package Logica;

public enum Tipos {
    VARCHAR,INTEGER,FLOAT,DATE,TIMESTAMP,DOUBLE,CHARACTER,CLOB,GRAPHIC,VARGRAPHIC,DBCLOB,BINARY,VARBINARY,BLOB,SMALLINT,BIGINT,DECIMAL,CHAR,REAL,TIME,DEFAULT
}
